from turtle import *
def window(x,y):
    penup()
    goto(x,y)
    pendown()
    begin_fill()
    color('blue')
    for i in range(2):
        forward(30)
        left(90)
        forward(15)           
        left(90)
    
    end_fill()
    

def domek(x,y):
    penup()
    goto(x,y)
    pendown()
    begin_fill()
    color('orange')
    forward(80)
    left(90)
    forward(150)
    left(90)
    forward(80)
    left(90)
    forward(150)
    end_fill()
    window(10+x,40+y)
    window(10+x,90+y)
    window(10+x,140+y)
    window(55+x,40+y)
    window(55+x,90+y)
    window(55+x,140+y)
    left(90)

def fonarik():
    penup()
    goto(-50,0)   
    pendown()
    color('black')
    pensize(3)
    left(90)
    forward(75)
    left(90)
    forward(30)
    begin_fill()
    circle(10)
    end_fill()
    left(180)

def dacha():
    penup()
    goto(120,0)
    pendown()
    color('brown')
    pensize(2)
    begin_fill()
    for i in range(4): 
        forward(100)
        left(90)
    end_fill()
    penup()
    goto(220,100)
    pendown()
    color('red')
    pensize(5)
    begin_fill()
    for i in range(3):
        right(-120)
        forward(100)
    end_fill()
